language: java
sudo: false
jdk:
  - oraclejdk7

# branches blacklist
branches:
  except:
    - gh-pages
    - mvn-repo

# custom build script and deployment
before_install: chmod +x script/deploy.sh
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
after_success: ./script/deploy.sh

deploy:
  provider: releases
  api-key: ${OAUTH2_DEPLOY_TOKEN}
  file-glob: true
  file: target/teamspeak3-api-*.jar
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: never
    on_failure: always
